### ISSUE TITLE
Unexpected OPTLINK Termination at EIP=0040F60A during building

### ISSUE THREAD

**Issue by bubnenkoff** [mysql-d/mysql-native#100]
I am getting next error when building project:

```
Unexpected OPTLINK Termination at EIP=0040F60A
EAX=03930000 EBX=00438C70 ECX=00000EE6 EDX=000002CE 
ESI=00000104 EDI=03930468 EBP=0019FF38 ESP=0019FEF0 
First=00402000
```

The project is buildable only if mysqldriver is commented in database.d:

import std.stdio;
import std.string;
import core.thread;
import ddb.postgres;
// import mysql; // <-- here
import vibe.d;
import config;

Tested on dmd 2.073 and 2.074. Windows 10. Demo project attached.

http://rgho.st/7j5LQLZxb

**Comment by bubnenkoff** [comment]
It's work only in release mode for me with
`dub --build=release`

**Comment by Abscissa** [comment]
This is a bug in optlink, please file at D's issue tracker: https://issues.dlang.org/enter_bug.cgi
