### ISSUE TITLE
Row to array issue

### ISSUE THREAD

**Issue by bubnenkoff** [mysql-d/mysql-native#101]
Could you look at this topics?
http://forum.dlang.org/thread/zpqthwybzkrqcsbonkba@forum.dlang.org
http://stackoverflow.com/questions/43452554/how-to-make-array-from-mysql-row-type

?

The main problem that without `.array` I do not getting result.

**Comment by Abscissa** [comment]
IIRC, this was answered in a different forum, so closing.
