### ISSUE TITLE
how to consumed or purged result?

### ISSUE THREAD

**Issue by bubnenkoff** [mysql-d/mysql-native#102]
I need to do two request one by other and then I want to process data. The problem that if I close result, I can't get access to data. If not close it, I can' do second request, because I am getting error:

` Data is pending on the connection. Any existing ResultRange must be consumed or purged before performing any other communication with the server.`

		ResultRange MySQLHistorySensorRange = mysqlconnection.query(`SELECT table_name FROM information_schema.tables where table_schema='` ~ config.mysqldbname ~ `' AND table_name LIKE 'historysensor%';`);
		// MySQLHistorySensorRange.close();
		ResultRange MySQLHistoryGPSRange = mysqlconnection.query(`SELECT table_name FROM information_schema.tables where table_schema='` ~ config.mysqldbname ~ `' AND table_name LIKE 'historygps%';`);
		// MySQLHistoryGPSRange.close();
		
		foreach(r;MySQLHistorySensorRange)
		{
			writeln(r);
		}

**Comment by Abscissa** [comment]
This is just the way MySQL connections work. It's not possible to issue a new SQL command on a connection before you've finished downloading all the results from the previous command. (See the documentation for query's return type: [ResultRange](http://semitwist.com/mysql-native-docs/v1.0.0/mysql/result/ResultRange.html).)

As the docs say, if you need to store the results you're downloading, although there are many ways to do it, I recommend using [std.array.array()](http://dlang.org/phobos/std_array.html#array).
