### ISSUE TITLE
Use $n in prepared statment instead of `?`

### ISSUE THREAD

**Issue by bubnenkoff** [mysql-d/mysql-native#106]
it's more handy to use $1 $2 ... instead of `?` in prepared query.
How it's done in postgresql driver https://github.com/pszturmaj/ddb/blob/master/examples/param.d#L34

At last I can control by eyes how many params I have.

I with to get same in mysql driver.

**Comment by Abscissa** [comment]
I don't know how it is with Postgres, but in MySQL/MariaDB, prepared statements are a feature of the actual MySQL/MariaDB DB server itself. It's not mysql-native's syntax, it's MySQL's syntax.

Even if (in theory) I were to wrap it in an optional translation layer, it would be non-trivial to do so without negating one of the benefits of prepared statements (ie, there's usually no need to do any allocations to build the SQL command), and it would just be an extra way to do the same thing. Additionally, unlike printf/writef, it's rare that an SQL statement would really need to be able to reorder or duplicate params. So it'd be a lot of downsides for very minimal benefit.
