### ISSUE TITLE
How create access to connection statment from many classes?

### ISSUE THREAD

**Issue by bubnenkoff** [mysql-d/mysql-native#109]
I need to get access to connection starment from several classes. I am looking right way. I found one example in another driver
https://github.com/denizzzka/vibe.d.db.postgresql/blob/master/example/example.d
here is `shared` keyword is used.

Is it's good solution? Can I do same in with this driver?

**Comment by Abscissa** [comment]
Shared is unrelated, that’s something for when you’re dealing with threads. Don’t bother with that, it’s tricky to get right anyway.

Just pass the connection as a parameter to any function that needs to use a connection. Don’t bother storing it in your classes, that’ll just make things difficult for no benefit.

(FWIW, this is applicable *any* time you’re working with a network connection to another machine, be it a database or anything else.)
