### ISSUE TITLE
use vibe.core.log when Have_vibe_d_core

### ISSUE THREAD

**Issue by SingingBush** [mysql-d/mysql-native#113]
when mysql-native is being used in a vibe-d application it may be handy to make use of vibe-d's logging. 

I'm currently seeing some problems when my application attempts to load some data from mariadb so I decided to increase the logging. I can see plenty from both my app and vibe-d but nothing from mysql-native.

It would be really handy if you guys were making use of _logDebug_, _logInfo_ and _logError_

**Comment by s-ludwig** [comment]
The ideal solution would probably be to use `std.experimental.logger` and plug that into vibe.d's log system. The main issue with this is that `std.experimental.logger` has no semantics defined for log levels < "info". It only has `trace`, with a number of unassigned integers to the nest level `info`, so mapping this to vibe.d is quite ambiguous.

**Comment by SingingBush** [comment]
That's also fine with me. (I created [vibe-d issue 1530](https://github.com/rejectedsoftware/vibe.d/issues/1530) for making use of [std.experimental.logger](https://dlang.org/phobos/std_experimental_logger.html))

It's unfortunate that it doesn't have a log level for debug, maybe that's something that should be raised on [the issue tracker](https://issues.dlang.org/enter_bug.cgi?bug_file_loc=http%3A%2F%2Fdlang.org/phobos/&bug_severity=enhancement&component=phobos&op_sys=All&priority=P3&product=D&rep_platform=All&short_desc=%5Bstd.experimental.logger%5D&version=D2)

**Comment by schveiguy** [comment]
Closed in #187
