### ISSUE TITLE
Row cannot be stored for later use when using a ResultSequence

### ISSUE THREAD

**Issue by schveiguy** [mysql-d/mysql-native#114]
On this page:
http://semitwist.com/mysql-native-docs/v1.0.0/mysql/commands/query.html

The statement "If you need random access to the resulting Row elements, simply call std.array.array() on the result" is dangerous.

I've dug down to determine whether strings are actually duplicated and they are not. See here: https://github.com/mysql-d/mysql-native/blob/master/source/mysql/protocol/packet_helpers.d#L358

Another part of this bug is that the cast is bad anyway. But at least the documentation should not recommend this mechanism.

**Comment by schveiguy** [comment]
Another place this is recommended: http://semitwist.com/mysql-native-docs/v1.0.0/mysql/result/ResultRange.html

**Comment by Abscissa** [comment]
That's fine. The buffer is not currently reused, rather a new one is allocated for each data packet:

https://github.com/mysql-d/mysql-native/blob/master/source/mysql/connection.d#L197

Admittedly, that's not the most heap-friendly approach and I'd like to improve on it (and the whole packet handling code could use a cleanup as well), but it's not a safety concern.

**Comment by schveiguy** [comment]
Oh, interesting. I have been writing my code assuming that a buffer is reused, so I am idup'ing all my strings as I put them into objects.

So you can close this, but one thing to keep in mind is if you *don't* update the docs, you have locked yourself into allocating a new buffer for every row. Something to think about.

BTW, I don't know if you saw my Dconf talk, one of my plans for my iopipe library is to make a wrapper for the mysql protocol, and get as efficient as possible. These are the kinds of things that keep me up at night 😜

**Comment by Abscissa** [comment]
> but one thing to keep in mind is if you don't update the docs, you have locked yourself into allocating a new buffer for every row. Something to think about.

Unless I also update the part that returns strings/arrays from the packet data ;) But yea.

> BTW, I don't know if you saw my Dconf talk, one of my plans for my iopipe library is to make a wrapper for the mysql protocol, and get as efficient as possible. These are the kinds of things that keep me up at night 😜

Haven't really gotten around to any of them yet, but I'll definitewly have to.

I did take a look at the front page for iopipe once, but couldn't quite grok what exactly it was solving. ANother reason I'll definitely have to take a look at that talk.
