### ISSUE TITLE
using `const(char[])` instead `string` for queries

### ISSUE THREAD

**Issue by Marenz** [mysql-d/mysql-native#121]
I already created a PR for the old API to change this, however it came back with the new API now.
Is there a specific reason for this or would you accept a PR that changes the parameters from `string` to `const(char[])`?

It would make using buffers for statements a lot easier.

**Comment by Abscissa** [comment]
Must've been an oversight on my part, apologies (typing `string` is practically muscle-memory for me). A new PR would be great.
