### ISSUE TITLE
`queryValue`: result of 1 row & field `NULL` check inconsistency / error

### ISSUE THREAD

**Issue by Marenz** [mysql-d/mysql-native#133]
The documentation for `queryValue()` says:

> If the query DID produce a result, but the value actually received is NULL, then result.isNull will be FALSE, and result.get will produce a Variant which CONTAINS null. Check for this with `result.get.type == typeid(typeof(null))`.

This turns out to be either false or at least incosistent. My Field type is `bigint(20) unsigned NULL`. I receive one row with one column and the value is null.

I do 

```
auto value = prep.queryValue();

assert(!value.isNull); // works
assert(value.get.type == typeid(typeof(null))); // fails
```

After some investigation it turns out the actual type is `void`. 
The reason for that is [this line](https://github.com/mysql-d/mysql-native/blob/4eaf5c6bb57d4ca852aa7fa5e8d2cd8810c0808a/source/mysql/result.d#L137)

It turns out, `binary` is true for my query thus the loop is skipped, thus [the setting to null](https://github.com/mysql-d/mysql-native/blob/4eaf5c6bb57d4ca852aa7fa5e8d2cd8810c0808a/source/mysql/result.d#L156) is never done

**Comment by Abscissa** [comment]
This is indeed a bug. It appears prepared statements aren't necessary to trigger it, the `BIGINT(20)` alone appears to be sufficient to trigger. (Actually, even `TINTINT` does it for me.)

**Comment by Abscissa** [comment]
Scratch that, my test was in error (was inserting a 1 instead of NULL). Prepared statement does appear to be needed to trigger the issue (at least in this particular case). `TINYINT` still triggers it too, though.

Fix on the way...in 3...2...1...
