### ISSUE TITLE
What can be reason of this error?

### ISSUE THREAD

**Issue by bubnenkoff** [mysql-d/mysql-native#137]
I am getting next error. What can be reason of it?

```
object.Exception@../../root/.dub/packages/vibe-d-0.8.1/vibe-d/core/vibe/core/drivers/libevent2.d(375): Failed to connect to host 127.0.0.1:3306: 7FAB0FAD404C
----------------
/usr/include/dmd/phobos/std/exception.d:420 pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, const(char[])) [0x9e19d2]
/usr/include/dmd/phobos/std/exception.d:388 pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong
) [0x9e194e]
../../root/.dub/packages/vibe-d-0.8.1/vibe-d/core/vibe/core/drivers/libevent2.d:375 @safe vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection vibe.core.dri
vers.libevent2.Libevent2Driver.connectTCP(vibe.core.net.NetworkAddress, vibe.core.net.NetworkAddress) [0xbd8875]
../../root/.dub/packages/vibe-d-0.8.1/vibe-d/core/vibe/core/net.d:116 @safe vibe.core.net.TCPConnection vibe.core.net.connectTCP(immutable(char)[], ushort, im
mutable(char)[], ushort) [0xc02782]
../../root/.dub/packages/mysql-native-1.1.0/mysql-native/source/mysql/connection.d:404 vibe.core.net.TCPConnection mysql.connection.Connection.defaultOpenSock
etVibeD(immutable(char)[], ushort) [0xa14407]
../../root/.dub/packages/mysql-native-1.1.0/mysql-native/source/mysql/connection.d:420 void mysql.connection.Connection.initConnection() [0xa144b7]
../../root/.dub/packages/mysql-native-1.1.0/mysql-native/source/mysql/connection.d:492 void mysql.connection.Connection.connect(mysql.protocol.constants.SvrCa
pFlags) [0xa148af]
../../root/.dub/packages/mysql-native-1.1.0/mysql-native/source/mysql/connection.d:607 mysql.connection.Connection mysql.connection.Connection.__ctor(mysql.pr
otocol.sockets.MySQLSocketType, std.socket.TcpSocket function(immutable(char)[], ushort)*, vibe.core.net.TCPConnection function(immutable(char)[], ushort)*, i
mmutable(char)[], immutable(char)[], immutable(char)[], immutable(char)[], ushort, mysql.protocol.constants.SvrCapFlags) [0xa14c2d]
../../root/.dub/packages/mysql-native-1.1.0/mysql-native/source/mysql/connection.d:574 mysql.connection.Connection mysql.connection.Connection.__ctor(mysql.pr
otocol.sockets.MySQLSocketType, immutable(char)[], immutable(char)[], immutable(char)[], immutable(char)[], ushort, mysql.protocol.constants.SvrCapFlags) [0xa
14a0d]
../../root/.dub/packages/mysql-native-1.1.0/mysql-native/source/mysql/connection.d:565 mysql.connection.Connection mysql.connection.Connection.__ctor(immutabl
e(char)[], immutable(char)[], immutable(char)[], immutable(char)[], ushort, mysql.protocol.constants.SvrCapFlags) [0xa149a3]
../../root/.dub/packages/mysql-native-1.1.0/mysql-native/source/mysql/pool.d:131 mysql.connection.Connection mysql.pool.MySQLPool.createConnection() [0xa17a0f
]
../../root/.dub/packages/vibe-d-0.8.1/vibe-d/core/vibe/core/connectionpool.d:94 @safe vibe.core.connectionpool.LockedConnection!(mysql.connection.Connection).
LockedConnection vibe.core.connectionpool.ConnectionPool!(mysql.connection.Connection).ConnectionPool.lockConnection() [0xa17f80]
../../root/.dub/packages/mysql-native-1.1.0/mysql-native/source/mysql/pool.d:127 vibe.core.connectionpool.LockedConnection!(mysql.connection.Connection).Locke
dConnection mysql.pool.MySQLPool.lockConnection() [0xa179a0]
source/database.d:28 void database.Database.MySQLConnect() [0x9b0146]
source/app.d:22 _Dmain [0x9a5cd9]
```

**Comment by bubnenkoff** [comment]
it seems that mariadb server go down...

**Comment by bubnenkoff** [comment]
Is it's possible that driver do now close connections or something like it? It's seems that there sis something related with driver, because I got this issue already few times.

Do I have some issue with my code https://github.com/bubnenkoff/pastcode ?

**Comment by Marenz** [comment]
I believe the mysql pool doesn't automatically reconnect like the 1.x.x version. I made a customized pool in my project that does
```
    auto get ( )
    {
        auto con = pool.lockConnection();

        if (con.closed())
            con.reconnect();

        return con;
    }
```

**Comment by Abscissa** [comment]
On October 8, 2017 7:21:33 PM EDT, "Mathias L. Baumann" <notifications@github.com> wrote:
>I believe the mysql pool doesn't automatically reconnect like the 1.x.x
>version. I made a customized pool in my project that does
>```
>    auto get ( )
>    {
>        auto con = pool.lockConnection();
>
>        if (con.closed())
>            con.reconnect();
>
>        return con;
>    }
>```

I think the auto-reconnecting was before any of the v1.x, IIRC. It had to go because it was causing some reliability problems.

**Comment by Marenz** [comment]
@Abscissa  May I ask what those reliability problems where? Because I am getting some very nasty `InvalidMemoryError` exceptions in unrelated tasks/callbacks/connections when I do a `reconnect()`

**Comment by Marenz** [comment]
this is what I found now: https://github.com/mysql-d/mysql-native/pull/138

**Comment by bubnenkoff** [comment]
Is it's possible that driver kill MySQL service? Every time when I run site that use this driver for about one week I am getting MySQL service failure. How I can check it?

**Comment by Abscissa** [comment]
> @Abscissa May I ask what those reliability problems where? Because I am getting some very nasty InvalidMemoryError exceptions in unrelated tasks/callbacks/connections when I do a reconnect()

Unfortunately, I don't remember exactly offhand. It was just a general pattern of severed connections leaving things in an undefined or inconsistent state.

One minor thing I do remember is that if you do reconnect, all prepared statements will be invalidated (on the server-side) and will need be be re-created. Although, TBH, that's closely releated to the problems combining prepared statements with connection pools - the MySQL protocol (rightly, IMO) ties prepares statements to individual connections, however, in light of connection pools and "reconnect()"s, that creates a need for a connection-independent abstraction for prepared statements, or at the very least, an on-connect callback.

But I seem to remember there being a lot of other, much more fundamental, lower-level problems as well, aside from prepared tatements.

TBH, I'm kind of surprised reconnect() survived the refactoring from v1.0.0. It's possible that may have been an oversight. OTOH, v1.0.0 fixed a LOT of reliability issues, so it could be that reconnect() and auto-reconnect might now be within reach again. I'll need to dig into that.

In any case, if there are specific issues (such as #138), than naturally, I want to do what I can to deal with it. But for now, for reliability's sake, my suggestion is that you may be better off avoiding reconnect() (allowing dead connections to say dead), and simply using a connection pool to replace dead connection with fresh new ones.

**Comment by Marenz** [comment]
Well, I am using a connection pool but I am also using prepared statements so I modified the pool to also store the info required to re-create the prepared statement on a different connection when it is requested.

I suppose I can try just creating a new connection instead of reconnecting though, that's easy enough to test.

Will the pool remove dead connections on its own?

**Comment by Marenz** [comment]
Looking a bit into it.. I don't actually see a way how I could replace a dead connection...

**Comment by Abscissa** [comment]
I'm going to close this as being too vague. *However* the discussion has raised another very good question that needs to be investigated (and fixed if necessary): What happens when a closed connection is released back to the pool? So I'm going to open a separate issue for that.
