### ISSUE TITLE
Considering deprecating duplicate exception names

### ISSUE THREAD

**Issue by Abscissa** [mysql-d/mysql-native#145]
Currently, all mysqln-native exception names are of the standard form `MySQL{exception name}Exception`. But since those get long and difficult to distinguish at a glance, they all have aliases of the form `MYX{exception name}`. Internally, the "MYX" form is used exclusively and, IMO, they've been MUCH nicer to use and a big win for both readability/writability.

To reduce potential confusion and to declutter the API, I'm considering deprecating the `MySQL{exception name}Exception` names (to later be removed entirely) and moving exclusively to the `MYX{exception name}` names.

Any opinions? Do people love it / hate it?

**Comment by Marenz** [comment]
I think it would help clarity
