### ISSUE TITLE
Make sure all ddox cross-linking is fixed.

### ISSUE THREAD

**Issue by Abscissa** [mysql-d/mysql-native#146]
The ddox comments need a once-over to fix any broken symbol cross-links by replacing (ex.) `FooBar` (no backticks) with `full.package.FooBar` (including backticks). No need to worry about readability, because newer versions of ddox will detect those and only show the symbol name, not the FQN.

IIRC, I *think* symbols defined within the same module can have their FQN and backticks omitted, but it might be better (and easier to avoid mistakes) to just be consistent and use both FQN and backticks everywhere. Unless that makes the documentation too hard to read within the .d files.

**Comment by Marenz** [comment]
That looks like mind numbing work. Kudos for finishing this.
