### ISSUE TITLE
Using prepared fails sometimes with "Acquiring waiter that is already in use "

### ISSUE THREAD

**Issue by bausshf** [mysql-d/mysql-native#153]
Sometimes when using a lot of prepared statements it will fail with "Acquiring waiter that is already in use" from down in "libasync", which causes the application to crash with an "AssertError".

I'm using vibe.d and MySQLPool and to retrieve a connection I use "lockConnection()" which I pass to "prepare":

Example:
```
auto connection = pool.lockConnection();
auto prepared = prepare(connection, sql);
```

**Comment by Abscissa** [comment]
@s-ludwig:This looks closer to your area of expertise than mine. Any insight?

**Comment by Abscissa** [comment]
This should be fixed in v2.0.0 as long as you don't use `prepareBackwardCompat` or `BackwardCompatPrepared`. Please re-open if you still experience this problem with v2.x.

**Comment by Abscissa** [comment]
Apparently still experienced, so reopening:
https://forum.dlang.org/thread/p7djc3$21hp$1@digitalmars.com?page=2#post-wzpqtxvtrgqqqrpfoukh:40forum.dlang.org

**Comment by Abscissa** [comment]
I've just tagged a new 'v2.2.1', please try that and also (as discussed on the NG) check that your code isn't accidentally using a `Connection` or a `ResultRange` after the original `LockedConnection` has gone out of scope. Let me know whether that tasks care of it..

**Comment by bausshf** [comment]
As far as I can see this is no longer an issue, at least not for me. I'll close this for now.
