### ISSUE TITLE
MySQLPool should automatically reopen any closed connections

### ISSUE THREAD

**Issue by Abscissa** [mysql-d/mysql-native#165]
What happens when a closed connection is released back to the pool?

This came up in the discussion for #137. This needs to be investigated, and fixes applied if necessary. I consider this a high priority.

**Comment by Abscissa** [comment]
From Vibe.d @ http://vibed.org/api/vibe.core.connectionpool/ConnectionPool
> Note that, after retrieving a connection with lockConnection, the caller has to make sure that the connection is actually physically open and to reopen it if necessary. The ConnectionPool class has no knowledge of the internals of the connection objects. 

So yea, need to make MySQLPool handle this.

**Comment by Abscissa** [comment]
Actually, turns out (contrary to my clearly unreliable memory!) mysql-native *already* automatically reconnects whenever a command is issued on a closed connection. Unittests indicate this is working reliably.

So technically, MySQLPool doesn't really need to check the connections it hands out after all. But it may be a good idea to do this anyway, just so receiving a closed connection from the pool doesn't freak anyone out, and so the connection process actually occurs up-front when expected instead of a surprise slowdown on the first command.

**Comment by Marenz** [comment]
Really? That would mean I can remove all my super hacky connection emplacement code..
I'll test this
