### ISSUE TITLE
Documentation for result ranges and connections

### ISSUE THREAD

**Issue by bausshf** [mysql-d/mysql-native#171]
As discussed per https://forum.dlang.org/post/p7qoh7$n7r$1@digitalmars.com

ResultRanges or Connections cannot be stored anywhere else other than locals and it should be documented properly.

**Comment by schveiguy** [comment]
I can't imagine that this is true. Connections are classes, so those can be stored anywhere.

ResultRanges are fine now, they just stop working once you execute another query.
