### ISSUE TITLE
Build app.d failed with UseConnPool

### ISSUE THREAD

**Issue by zpah** [mysql-d/mysql-native#190]
mysql-native-2.2.2/mysql-native/source/app.d(36,14): Error: undefined identifier MySqlPool, did you mean class MySQLPool?
DMD64 D Compiler v2.083.0
DUB version 1.12.0, built on Dec 19 2018

**Comment by schveiguy** [comment]
oof. This should have been fixed a while ago. Sorry, and thanks for the report.
