### ISSUE TITLE
build issues on various compiler versions

### ISSUE THREAD

**Issue by SingingBush** [mysql-d/mysql-native#197]
on my fork I [added all the compiler versions since 2.0.80](https://github.com/SingingBush/mysql-native/commit/c44c3b5d67b5ffc9ea39e0ed829161cd8ff85120) to see how the travis-ci build handles it:

https://travis-ci.org/SingingBush/mysql-native/builds/579444314

Things are not great. I've said before (#141 drop support for old compiler versions) that it's an unnecessary maintenance burden. Do you really need to support all the way back to dmd 2.068.2 (Sep 2015) to the latest dmd 2.087.1 version?

**Comment by Abscissa** [comment]
On September 1, 2019 10:44:07 AM EDT, Samael <notifications@github.com> wrote:
>on my fork I [added all the compiler versions since
>2.0.80](https://github.com/SingingBush/mysql-native/commit/c44c3b5d67b5ffc9ea39e0ed829161cd8ff85120)
>to see how the travis-ci build handles it:
>
>https://travis-ci.org/SingingBush/mysql-native/builds/579444314
>
>Things are not great. I've said before (#141 drop support for old
>compiler versions) that it's an unnecessary maintenance burden. Do you
>really need to support all the way back to dmd 2.068.2 (Sep 2015) to
>the latest dmd 2.087.1 version?

Just took a quick look at several of those failures, including the one using the latest dmd. They all still compiled (just with one non-fatal deprecation that looks trivial to fix without affecting backwards compatibility). The failures I do see are failures to connect to the socket, which in my experience pretty much always indicates some sort of configuration problem, like an incorrect connection string or db server not running for some reason. It's highly unlikely for compiler/phobos changes to cause this.

**Comment by SingingBush** [comment]
I've done a little digging. Seems there is an issue with travis-ci and newer versions of Ubuntu/Mariadb that I hope to have sorted now. Will have to see how this build does:
https://travis-ci.org/SingingBush/mysql-native/builds/579489019

**Comment by Abscissa** [comment]
Now fixed in master.
