### ISSUE TITLE
Expose vibe.d connection pool's removeUnused function

### ISSUE THREAD

**Issue by schveiguy** [mysql-d/mysql-native#200]
Every time my vibe.d server shuts down, I get a bunch of messages such as:

```
Warning (thread: main): leaking eventcore driver because there are still active handles
   FD 7 (streamSocket)
   FD 13 (streamSocket)
   FD 14 (streamSocket)
```

These are due to open MySQL connection pool connections. I want to get rid of these, and vibe.d included the nice feature to close all connections not in use [here](https://github.com/vibe-d/vibe-core/pull/143).

But I can't use it, because `m_pool` is private in `MySQLPool`. This functionality should be exposed.

**Comment by schveiguy** [comment]
PR: #210

**Comment by Abscissa** [comment]
#210 is merged
