### ISSUE TITLE
Travis failure on MariaDB 10.4

### ISSUE THREAD

**Issue by Abscissa** [mysql-d/mysql-native#208]
Suspect this is a travis issue rather than mysql-native issue. Maybe due to using travis 'trusty'? (Upgrading from trusty to xenial or bionic is blocked by [this travis issue](https://travis-ci.community/t/failures-installing-mariadb-10-2-on-xenial/5284/3)).

Failure:
```
Running ./bin/mysql-native-test-unittest-vibe 
mysql.exceptions.MYXReceived@source/mysql/protocol/comms.d(528): MySQL error: Cannot load from mysql.proc. The table is probably corrupted
```

**Comment by SingingBush** [comment]
travis is no longer used since #228 is now merged (see #227). Maria db is used in the test pipeline as well as MySQL 5.7 so this issue can now be closed.
