### ISSUE TITLE
column typed as int(11) becomes long

### ISSUE THREAD

**Issue by schveiguy** [mysql-d/mysql-native#213]
I have a column that I'm pretty sure I created as type `INT` in my sql statement, and when looking at the type information from `show table` it shows as `INT(11)` which I gather is a 32-bit integer.

When I select data from this table, mysql-native is populating the column as a `long` and not an `int`.

I'm not sure *at all* about the protocol or if this is discernible from the packet data, but I expected for sure that I could do `row[column].get!int` and it would work, but it doesn't. Is there something I'm missing? Or is there a bug here?

**Comment by Abscissa** [comment]
Hmm, I'll look into it. Can you check the behavior on the same server when you do the same through either the official mysql/mariadb cli, or another tool using the official client libs?

**Comment by schveiguy** [comment]
This is directly from the `mysql` tool. I wish it would just say "32-bit", but it says `INT(11)`.

**Comment by schveiguy** [comment]
I will note, currently, I'm using php to create the column. But it's just sending SQL to the server, so I'm pretty sure it should be INT.

**Comment by schveiguy** [comment]
More info: This works, and it confuses the shit out of me. I fully expected this to fail. (obviously xxx is used instead of the real username/password/database)

```D
import mysql;

void main()
{
    auto conn = new Connection("127.0.0.1", "xxx", "xxx", "xxx");
    conn.exec("DROP TABLE IF EXISTS testtable");
    conn.exec("CREATE TABLE testtable (blah INT(11))");
    conn.exec("INSERT INTO testtable VALUES (1), (2), (3)");
    foreach(row; conn.query("SELECT * FROM testtable"))
    {
        import std.stdio;
        writeln(row[0].get!int);
    }
}
```

**Comment by schveiguy** [comment]
Oh wait, I think I know why this isn't working locally. The column is actually not a stored but calculated column. Which likely is being expanded to the largest type possible.

**Comment by schveiguy** [comment]
Yep, confirmed. This fails:

```D
import mysql;

void main()
{
    auto conn = new Connection("127.0.0.1", "xxx", "xxx", "xxx");
    conn.exec("DROP TABLE IF EXISTS testtable");
    conn.exec("CREATE TABLE testtable (blah INT(11))");
    conn.exec("INSERT INTO testtable VALUES (1), (2), (3)");
    foreach(row; conn.query("SELECT blah * 5 as val FROM testtable"))
    {
        import std.stdio;
        writeln(row[0].get!int);
    }
}
```
