### ISSUE TITLE
Wrong number of bytes read when preparing a statement

### ISSUE THREAD

**Issue by nomad-software** [mysql-d/mysql-native#22]
I'm running some code in production and occasionally i get the following exception from connection.d when preparing a statement (command.prepare()):

    Wrong number of bytes read

Then interacting with the database after that throws:

    Server packet out of order

Is there a common cause of these errors or would you guess it's a bug in connection? I know that's a bit vague but i'm dealing with a large code base and just wondering where to begin finding the cause.

**Comment by Temtaime** [comment]
Hi !
I hit this problem too frequently.
Too sad that there's no solution.

**Comment by Temtaime** [comment]
I've looked at the code.
The error happens when query lasts too long.

It's just a chance that error happens only sometimes.
There's wrong code.

Replacing common.d:117:
        auto bytesRead = socket.receive(dst); // receive waits not until ALL data received, but only part of it !
        enforceEx!MYX(bytesRead == dst.length, "Wrong number of bytes read");
        enforceEx!MYX(bytesRead != socket.ERROR, "Received std.socket.Socket.ERROR");

with this:

        for(size_t len; len != dst.length; ) {
			auto k = socket.receive(dst[len..$]);
			enforceEx!MYX(k != 0, "Server closed the connection");
			enforceEx!MYX(k != socket.ERROR, "Received std.socket.Socket.ERROR");
			len += k;
        }

Fully fixed an error for me.

**Comment by sshamov** [comment]
Done.

Coincidently, it also fixes the test case shown above by @Abscissa.
His test query was preparing repeatedly all night long on my server. No exception was thrown.
Apparently, this issue could be closed.

**Comment by nomad-software** [comment]
Great work guys, thanks to all involved.
