### ISSUE TITLE
Column name is empty in result row if column value was NULL

### ISSUE THREAD

**Issue by webloft** [mysql-d/mysql-native#222]
Cannot retrieve colum name with Row.getName() because it's skipped in ctorRow() if value was null.

**Comment by webloft** [comment]
This bug is still present. Please add just the line

`_names[i] = rh[i].name;`

in comms.d:665 in ctorRow()

It adds the field value but forgets to set the name for the field before the continue statement.

**Comment by schveiguy** [comment]
Yeah, I actually was going to look into this, as I noticed it recently. I had forgotten there was already a bug report!
