### ISSUE TITLE
Consider not to use Variant

### ISSUE THREAD

**Issue by webloft** [mysql-d/mysql-native#223]
There is a bug or feature that TypeInfo does not pass DLL boundaries correctly:
eg: https://issues.dlang.org/show_bug.cgi?id=20579

If you want to compile this library in a DLL you got a problem:

Variant does not allow fetching the data if it cannot checking the type. 
Then you getting errors like "attempting to use incompatible types int and int".
You can also not checking yourself because TypeInfo.toString() returns "".
You cannot even force Variant to fetch your data.

It's not likely that the bug will be fixed in near future.
Using an own data exchange struct is not a big deal. The language feature void[] makes it possible to accept all kind of arrays. Structs can be copied as S[].

**Comment by schveiguy** [comment]
This will be mitigated on the new release in which the `@safe` variant of mysql-native will use something other than Variant. I will update this report when it's ready, and you can try it out.

**Comment by webloft** [comment]
I'm exited about how you will solve the foreign runtime GC issue with this task because that would be the next problem using a DLL. Currently, I'm not avoiding the GC and just .dup it what's needed as soon the DLL function returns. But it needs to test the data type via toString() on every row returned.

Technically speaking, this is not a problem of this library but it would be nice if the DLL function could accept and return this variant without headache and custom wrappers.

**Comment by schveiguy** [comment]
Just taking a peek at old issues, this should be resolved if you use the `@safe` version of mysql-native.
