### ISSUE TITLE
updating from 3.1.0 to 3.2.0 is a breaking change

### ISSUE THREAD

**Issue by SingingBush** [mysql-d/mysql-native#272]
I was reading the [safe migration guide](https://github.com/mysql-d/mysql-native/blob/master/SAFE_MIGRATION.md) which states that in 3.2.0 the default modules/packages will pull in the unsafe versions of the API to maintain backwards compatibility. 

On updating and doing a build though I got errors:

```
./../../.dub/packages/mysql-native-3.2.0/mysql-native/source/mysql/impl/prepared.d(156,20): Error: none of the overloads of `opAssign` are callable using argument types `(byte[])`, candidates are:
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d(147,7):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(TaggedAlgebraic!(_MYTYPE) other)`
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d-mixin-140(149,9):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(ubyte[] value)`
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d-mixin-140(165,9):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(const(ubyte)[] value)`
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d-mixin-140(181,9):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(typeof(null) value)`
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d-mixin-140(197,9):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(bool value)`
../../../.dub/packages/mysql-native-3.2.0/mysql-native/source/mysql/impl/prepared.d(156,20):        ... (34 more, -v to show) ...
../../../.dub/packages/mysql-native-3.2.0/mysql-native/source/mysql/impl/prepared.d(327,15): Error: template instance `mysql.impl.prepared.SafePrepared.setArg!(byte[])` error instantiating
source/ddbc/drivers/mysqlddbc.d(705,38):        instantiated from here: `setArg!(byte[])`
```

I tried changing all my imports to be the explicit `mysql.unsafe.*` versions but the error remained the same. For now it seems [ddbc](https://github.com/buggins/ddbc) will need to stay on 3.1.0

ddbc also uses `std.variant` everywhere and potentially could do with some work to use `@safe` code. Not expecting to get time to do that any time soon though

**Comment by schveiguy** [comment]
For sure that is a bug. If it worked with the previous version, it should work with this one. I'll have to check if there's any difference with using `byte` vs `ubyte`, and if so, add another type into the tagged algebraic. If not, then avoiding another name for the same thing is ideal, so I'll just make a conversion for the unsafe -> safe converters.

**Comment by SingingBush** [comment]
there was a similar error for one of the other types. Think it may have been SysTime

**Comment by schveiguy** [comment]
Just remembering about this. It's going to have to wait a bit, as I'm in a crunch for a few things right now.

**Comment by schveiguy** [comment]
Looking at the old switch statement, ubyte[] and byte[] are handled identically. So I can just do a cast in the conversion from variant.

Have you verified which other type was causing problems?

**Comment by schveiguy** [comment]
I did a thorough test of all the types listed. `byte[]` is the only problematic case. There's also a `Time` case, but that type no longer exists I think.
