### ISSUE TITLE
std logger changes in dmd 2.101

### ISSUE THREAD

**Issue by SingingBush** [mysql-d/mysql-native#273]
Hi, this issue https://github.com/buggins/ddbc/issues/112 was raised in DDBC due to breaking changes for the std logger. I suspect that means mysql-native will also be affected

https://dlang.org/changelog/2.101.0.html#logger_remove_compile_time_loglevel
https://dlang.org/changelog/2.101.0.html#logger_sharedLog_returning_shared_logger

**Comment by SingingBush** [comment]
changing imports to something like this should be fine:

```d
static if(__traits(compiles, (){ import std.logger; } )) {
    import std.logger ; sharedLog;
} else {
    import std.experimental.logger ; sharedLog;
}
```

**Comment by schveiguy** [comment]
Yeah, looks good.

**Comment by schveiguy** [comment]
Fixed in #274 had to fix to get the CI to pass.

**Comment by SingingBush** [comment]
is it possible to get a v3 based release out with these changes

**Comment by schveiguy** [comment]
I was hoping to get in also the fixes for #272 but I can do a point release now.

**Comment by SingingBush** [comment]
thanks. I still need #272 as well for ddbc but 3.2.1 will potentially help other users

**Comment by schveiguy** [comment]
Yeah, I need to spend some time on it, sorry for the delay

**Comment by SingingBush** [comment]
No problem. I have a mountain of bugs to work through myself
