### ISSUE TITLE
Can't download mutliple rows

### ISSUE THREAD

**Issue by MightyPrinny** [mysql-d/mysql-native#282]
Hi, I've been using this with no functional problems, but it seems very slow for downloading lots of rows from an external server, I didn't see a way to download mulitiple rows at once, I tried getting the elements from ResultRange by chunks of 100, but that only seems to save ram (compared to using .array), which makes sense if it has to wait before downloading the next row, if there's another way please let me know.

**Comment by schveiguy** [comment]
The data is transmitted via TCP, so it moves as fast as the network can go. I have not had any problems downloading tens of thousands of rows. Can you compare to another client with the same query and let me know what the difference is?

**Comment by MightyPrinny** [comment]
Sorry, you're right ,  I forgot to test a few things, I'm using a VPN and l had measured the network speed of the vpn server and mine, but not between both through the VPN and it's a huge difference, the time it takes mysql-native and the mysql command line client is pretty much the same.

**Comment by schveiguy** [comment]
Great, thanks for checking!
