### ISSUE TITLE
Unsupported SQL type NEWDECIMAL

### ISSUE THREAD

**Issue by punkUser** [mysql-d/mysql-native#39]
Hi guys,

When I try to use a query with an aggregate function in the select list (notable "SUM(field)") it seems that MySQL tries to return it as a "NEWDECIMAL" type which mysql-native doesn't currently seem to support. For reference, my MySQL server version is "5.5.29-0ubuntu0.12.04.1".

As a test, I added the following to the switch statement in consumeIfComplete:
case SQLType.NEWDECIMAL:
return packet.consumeIfComplete!int(false, unsigned);
... which seems to work ok for my simple test case. I'm not sure if "long" or something else would be more appropriate here... the MySQL protocol docs on NEWDECIMAL are pretty sparse to say the least :)

Have I got some sort of weird config going on or is this a known issue? If so, is the above implementation legitimate?

Cheers!

**Comment by Abscissa** [comment]
While looking into #111 (which appears to be related to this), I managed to find some NEWDECIMAL documentation, thatnks to MariaDB:

https://mariadb.com/kb/en/mariadb/resultset-row/#decimal-binary-encoding

But based on that, I'm surprised that treating NEWDECIMAL as a DOUBLE ever worked at all. I'll have to look into that.
