### ISSUE TITLE
Possible dangling connection after each request

### ISSUE THREAD

**Issue by s-ludwig** [mysql-d/mysql-native#41]
According to rejectedsoftware/vibe.d#593 it may be the case that connections don't get freed properly.

**Comment by Abscissa** [comment]
I'm a bit unclear on this. Can you provide a way to check for this?

**Comment by schveiguy** [comment]
Closing, as I doubt I can reproduce this 8-year-old bug, and it may not exist any more. Please reopen if you feel it still needs attention.
