### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by bhechinger** [mysql-d/mysql-native#46]
I've mostly stumbled through getting things working by reading the mysqln documentation, but there are minor differences which has made this to be an interesting task.

I would like to ask that at the very least some basic documentation be provided.

Additionally I think it would be nice to have documentation that is more specific to vibe.d and Phobos. For example, when using this with vibe.d, what's the best way to setup the connection to the DB to be accessed from the worker fibers.

Thanks for outstanding software!

**Comment by whitebyte** [comment]
I've made some pretty basic docs here: http://whitebyte.github.io/mysql-native/
You can add it to this repo by creating "gh-pages" branch and merging https://github.com/whitebyte/mysql-native/tree/gh-pages into it. it will also enable me (or other contributors) to make PRs to docs, not the code itself.

**Comment by whitebyte** [comment]
BTW, API docs can be hosted at github.io as well, see http://buggins.github.io/dlangui/ddox/ for example.

**Comment by schveiguy** [comment]
Sorry to piggy back here, but is there any place I can view generated API docs? It's annoying to have to fumble around to find where some type is in this tree.

**Comment by whitebyte** [comment]
Since docs are in pretty decent state as of 1.0,  this issue should be closed maybe?

**Comment by Abscissa** [comment]
@schveiguy: There wasn't before, but there is now: http://semitwist.com/mysql-native

@whitebyte: Yes, probably time for that. I do still want to flesh out the docs with more examples, but I think that calls for a separate issue.
