### ISSUE TITLE
Access Violation in makeToken

### ISSUE THREAD

**Issue by Extrawurst** [mysql-d/mysql-native#53]
in line:

```
auto pass1 = sha1Of(cast(const(ubyte)[])_pwd);
```

right when i try to open the first connection...
tested on win32 with dmd 2.066.1 and vibe.d 0.7.21

**Comment by Abscissa** [comment]
Is this still an issue?

**Comment by Extrawurst** [comment]
havent tried for ages and there was a workaround. closing for now
