### ISSUE TITLE
Newly added "escape" module missing in package.d

### ISSUE THREAD

**Issue by whitebyte** [mysql-d/mysql-native#63]
...so right now we can't just
```d
import mysql;
```
to access them until it's imported explicitly by
```d
import mysql.escape;
```

**Comment by Abscissa** [comment]
I think I might have been slightly hasty in merging the escape module, as I'm having trouble compiling and running the unittest. That will need to get sorted out first, before adding it to package.d

**Comment by Marenz** [comment]
My fault, I am using a function in the unittest that isn't imported
