### ISSUE TITLE
Allow limiting number of connections in connection pool

### ISSUE THREAD

**Issue by schveiguy** [mysql-d/mysql-native#74]
In `MysqlDB`, the vibe.d `ConnectionPool` type is used to manage connections.

However, the limit on the number of connections is unspecified, and defaults to `uint.max`.

What is the point of using connection pool if you aren't going to limit connections? I thought that was the entire point. If you don't limit, and don't close connections you are done with, you run the risk of having tens of thousands of connections open to the DB. So you need to close the connections after use. But then, you are simply saving the cost of allocation/deallocation, which isn't very much (and replacing it with a linear search through the connection pool + hash lookups when allocating a new one).

**Comment by Abscissa** [comment]
Fixed in v1.0.0
