### ISSUE TITLE
Use test/common as basis for a more convenient API

### ISSUE THREAD

**Issue by dhasenan** [mysql-d/mysql-native#83]
It looks like the tests use a slew of convenience functions provided in mysql/test/common.d. This suggests that the API provided is inconvenient. It also means that the tests can't easily be used as a guide for how to use the regular API.

Since the tests use a more convenient API, it would be nice if the primary API were augmented with those additions.

**Comment by Abscissa** [comment]
I agree. I just wanted to put a little but more thought into them before exposing them publically.

For reference, the functions in question are here:
https://github.com/mysql-d/mysql-native/blob/master/source/mysql/test/common.d#L102

**Comment by Abscissa** [comment]
Fixed in v1.0.0
