### ISSUE TITLE
Make membership in the mysql-d group public

### ISSUE THREAD

**Issue by dhasenan** [mysql-d/mysql-native#88]
I would like to tell: if someone responds to an issue, are they speaking authoritatively? If I submit a pull request and someone responds, is this some random person or a maintainer?

But membership is private, so I can't tell.

**Comment by Abscissa** [comment]
Ah, I wasn't aware of that. Thanks. Should be fixed now.

FWIW, I'm the primary maintainer at this point. Sonke doesn't really use mysql much anymore.
