### ISSUE TITLE
Still fetches vibe.d even without "-version=Have_vibe_d_core"

### ISSUE THREAD

**Issue by whitebyte** [mysql-d/mysql-native#94]
`dependency "mysql-native" version="~>1.0.0"`
dub downloads vibed- 0.7.30 and puts it into dub.selection.json
Is it expected behavior?

**Comment by Abscissa** [comment]
On February 28, 2017 12:40:04 PM EST, Anton Pastukhoff <notifications@github.com> wrote:
>`dependency "mysql-native" version="~>1.0.0"`
>dub downloads vibed- 0.7.30 and puts it into dub.selection.json
>Is it expected behavior?

mysql-native's dub.sdl has vibed set as an optional dependency, so if vibe's automatically being pulled in, that sounds like a bug in dub (as long as you're sure none of your other dependencies, if any, are pulling in vibe). I'll look into it.

**Comment by Abscissa** [comment]
I'm able to reproduce the issue. Filed as: https://github.com/dlang/dub/issues/1089

**Comment by whitebyte** [comment]
Thanks, I'm closing this one since it's actually an upstream issue/
